# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Musings on Software Engineering
email: ftriboix@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about software engineering, development
  processes, best practices and anything
  that helps to produce working software that delights clients.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabricetriboix.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: fabricetriboix

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-83214072-1
