# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Business of Software Engineering
email: ftriboix@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about a subject that I think is overlooked too many times:
  How technical decisions at software engineering level impact the
  long-term profitability of a business? Often, managers are clueless
  about the technical aspects of software engineering, and technical
  people either don't care about the business or are often unaware of how
  their work can have an indirect but very tangible impact, either
  positive or negative, on the business that employs them.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabricetriboix.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: fabricetriboix

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-83214072-1
